# Generated by Django 3.2.7 on 2021-09-05 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KawasanBerikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_KB', models.CharField(max_length=100)),
                ('Alamat', models.CharField(max_length=100)),
                ('Kabupaten', models.CharField(choices=[('t', 'Tasikmalaya'), ('g', 'Garut')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JenisDocument', models.CharField(choices=[('LapBul', 'Laporan Bulanan'), ('LapKegBul', 'Laporan Kegiatan Bulanan')], max_length=10)),
                ('Tahun', models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='2021', max_length=4)),
                ('Bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=10)),
                ('PDF', models.FileField(upload_to='laporan/pdfs')),
                ('KawasanBerikat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.kawasanberikat')),
            ],
        ),
    ]
